steps:
  # 1. Build Backend API
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/jejakhijau-api:$COMMIT_SHA', '-f', 'Dockerfile', '.']
  
  # 2. Build Frontend Web (User) - Inject VITE_API_URL
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/jejakhijau-web:$COMMIT_SHA', '--build-arg', 'VITE_API_URL=$_API_URL', '-f', 'Dockerfile.web', '.']

  # 3. Build Frontend Admin - Inject VITE_API_URL
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/jejakhijau-admin:$COMMIT_SHA', '--build-arg', 'VITE_API_URL=$_API_URL', '-f', 'Dockerfile.admin', '.']

  # 4. Push Images to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/jejakhijau-api:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/jejakhijau-web:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/jejakhijau-admin:$COMMIT_SHA']

  # 5. Deploy API to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'jejakhijau-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/jejakhijau-api:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GEMINI_API_KEY=$_GEMINI_API_KEY,DATABASE_URL=$_DATABASE_URL,JWT_SECRET=$_JWT_SECRET,NODE_ENV=production'

  # 6. Deploy Web to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'jejakhijau-web'
      - '--image'
      - 'gcr.io/$PROJECT_ID/jejakhijau-web:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      - '--allow-unauthenticated'
      - '--port'
      - '80'

  # 7. Deploy Admin to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'jejakhijau-admin'
      - '--image'
      - 'gcr.io/$PROJECT_ID/jejakhijau-admin:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      - '--allow-unauthenticated'
      - '--port'
      - '80'

substitutions:
  _REGION: 'asia-southeast2'   # Jakarta Region
  _API_URL: 'https://jejakhijau-api-dummy.a.run.app' # Akan diisi di Trigger nanti
  _GEMINI_API_KEY: 'AIzaSyAxQFdpXqvGTbyzJcM5cxvgVe1dpJgDvb0'
  _DATABASE_URL: 'postgresql://postgres:qG%2FJt%7Bq%40V-%5E%3D4%7B5_@34.128.83.123:5432/jejakhijau'
  _JWT_SECRET: '528f1e12a209b428543828d902099db4'

options:
  logging: CLOUD_LOGGING_ONLY
